version: "3.9"
services:

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "loudstream"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
