"""Add published column to musics and albums

Revision ID: 2a0c492c6d2d
Revises: dbb7fe1cefe8
Create Date: 2022-10-11 21:19:21.652421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0c492c6d2d'
down_revision = 'dbb7fe1cefe8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('musics', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musics', 'published')
    op.drop_column('albums', 'published')
    # ### end Alembic commands ###
