"""Frist revision

Revision ID: 901284fe86ca
Revises: 
Create Date: 2022-10-11 15:27:18.424034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901284fe86ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
